name: Publish

on:
  push:
    branches: [master]

jobs:
  validate_and_publish:
    name: Validate and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .npmrc file
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Yarn
        if: ${{ env.ACT }}
        run: npm install yarn -g

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build, Lint, Test
        run: yarn run validate

      - name: Upload Coverage - Shared
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/shared/coverage/lcov.info
          flags: shared
          name: shared
          fail_ci_if_error: false

      - name: Delay between coverage uploads
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

      - name: Upload Coverage - Server
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/server/coverage/lcov.info
          flags: server
          name: server
          fail_ci_if_error: false

      - name: Delay between coverage uploads
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

      - name: Upload Coverage - Joiful
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/joiful/coverage/lcov.info
          flags: joiful
          name: joiful
          fail_ci_if_error: false

      - name: Delay between coverage uploads
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

      - name: Upload Coverage - Express
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/express/coverage/lcov.info
          flags: express
          name: express
          fail_ci_if_error: false

      - name: Delay between coverage uploads
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

      - name: Upload Coverage - Client
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/client/coverage/lcov.info
          flags: client
          name: client
          fail_ci_if_error: false

      - name: Delay between coverage uploads
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

      - name: Upload Coverage - React
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/react/coverage/lcov.info
          flags: react
          name: react
          fail_ci_if_error: false

      - name: Create Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.email "release-bot@typepoint.github.io"
          git config user.name "Release Bot"
          yarn lerna publish --yes --conventional-commits --no-verify-access
