name: Validate

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn
        if: ${{ env.ACT }}
        run: npm install yarn -g

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build, Lint, Test
        run: yarn validate
